### ISSUE TITLE
 “dataanalysis.h”: No such file or directory

### ISSUE THREAD

**Issue by pengmy001** [HPSCIL/cuFSDAF#2]
Dear cuFSDAF authors:
When i build cuFSDAF.exe there seem to be an error:  C1083 “dataanalysis.h”: No such file or directory
It seems like I don't have this file and I did not find it on the internet. Is this file from GDAL or cuFSDAF?

**Comment by GaoHuanCUG** [comment]
> 
> 
> Dear cuFSDAF authors:
> When i build cuFSDAF.exe there seem to be an error: C1083 “dataanalysis.h”: No such file or directory
> It seems like I don't have this file and I did not find it on the internet. Is this file from GDAL or cuFSDAF?

"dataanalysis.h" is a head file of ALGLIB. You may add the include path of ALGLIB when compiling.  
Besides, we added some details of compilation in README, which may help you to solve this error.

**Comment by pengmy001** [comment]
OK thanks. Problem solved.
However, I encountered another problem. The program didnt have any ouput files.
I debuged it and  in this sentence 

```
if (strcmp(label, "IN_F1_NAME") == 0)
				sscanf_s(tokenptr, "%s", par->InputF1);
```

find out this error:

> 0x7A0DDDF4 (ucrtbased.dll)处(位于 cuFSDAF.exe 中)引发的异常: 0xC0000005: 写入位置 0x00A0F000 时发生访问冲突。
> 
> 如有适用于此异常的处理程序，该程序便可安全地继续运行。

I dont know c++ very well but I think there might be something wrong with the function sscanf_s. 
I thought it might be the problem of utf-8 but after I changed it there are still problems.
The same problems occur when i ran cuSTARFM.
Hope you can help me.

**Comment by pengmy001** [comment]
Also i checked the value of par->InputF1 and it is

> 0x00c6d118 "屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯

**Comment by GaoHuanCUG** [comment]
> 
> 
> Also i checked the value of par->InputF1 and it is
> 
> > 0x00c6d118 "屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯



> 
> 
> OK thanks. Problem solved.
> However, I encountered another problem. The program didnt have any ouput files.
> I debuged it and in this sentence
> 
> ```
> if (strcmp(label, "IN_F1_NAME") == 0)
> 				sscanf_s(tokenptr, "%s", par->InputF1);
> ```
> 
> find out this error:
> 
> > 0x7A0DDDF4 (ucrtbased.dll)处(位于 cuFSDAF.exe 中)引发的异常: 0xC0000005: 写入位置 0x00A0F000 时发生访问冲突。
> > 如有适用于此异常的处理程序，该程序便可安全地继续运行。
> 
> I dont know c++ very well but I think there might be something wrong with the function sscanf_s.
> I thought it might be the problem of utf-8 but after I changed it there are still problems.
> The same problems occur when i ran cuSTARFM.
> Hope you can help me.



> 
> 
> OK thanks. Problem solved.
> However, I encountered another problem. The program didnt have any ouput files.
> I debuged it and in this sentence
> 
> ```
> if (strcmp(label, "IN_F1_NAME") == 0)
> 				sscanf_s(tokenptr, "%s", par->InputF1);
> ```
> 
> find out this error:
> 
> > 0x7A0DDDF4 (ucrtbased.dll)处(位于 cuFSDAF.exe 中)引发的异常: 0xC0000005: 写入位置 0x00A0F000 时发生访问冲突。
> > 如有适用于此异常的处理程序，该程序便可安全地继续运行。
> 
> I dont know c++ very well but I think there might be something wrong with the function sscanf_s.
> I thought it might be the problem of utf-8 but after I changed it there are still problems.
> The same problems occur when i ran cuSTARFM.
> Hope you can help me.



> 
> 
> Also i checked the value of par->InputF1 and it is
> 
> > 0x00c6d118 "屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯屯

Would you mind leaving me a personal E-mail so that I could see more details about your problem? You could send me an E-mail (ghcug14@cug.edu.cn).
