### ISSUE TITLE
How to compile ALGLIB？

### ISSUE THREAD

**Issue by ydlam** [HPSCIL/cuFSDAF#3]
The project has been reporting errors about ALGLIB, so I want to compile ALGLIB, but I can't find out how to compile ALGLIB.Can you answer that?

**Comment by GaoHuanCUG** [comment]
The way to compile ALGLIB :
1. For Linux:
`$ cd YourLibSourceCodePath    // e.g., cuFSDAF/Code/alglib/`
`$ gcc -c *.cpp`
`$ ar rcs libalglib.a *.o`
Then, use the static lib file "libalglib.a" to compile cuFSDAF.
2. For Windows (using VS2017 as examples):
(1) Create a new static library project, named "ALGLIB"
(2) Add source codes into the project, and add the include path of ALGLIB
(3) Build the project
Then, you may find file "ALGLIB.lib" in your project's path

**Comment by ydlam** [comment]
ok thanks.
