### ISSUE TITLE
编译是提示出现错误，在FSDAF.cpp:760:25 dataanalysis.h:5393:6: note:   candidate expects 4 arguments, 6 provided

### ISSUE THREAD

**Issue by 765302995** [HPSCIL/cuFSDAF#5]
Hi:
我在编译的时候发出现这个问题
![image](https://github.com/HPSCIL/cuFSDAF/assets/46253104/c256bebe-2b0a-4c03-8f75-f7d8b1b61180)
我已经把ALGLIB 4.00.0 C++版本复制到cuFDAF/src文件中，请问这个应该怎么解决？

**Comment by 765302995** [comment]
[alglib-cpp.zip](https://github.com/HPSCIL/cuFSDAF/files/12429657/alglib-cpp.zip)

**Comment by 765302995** [comment]
个人觉得是alglib的版本问题，但是无法下载3.13版本，可以提供一个下载地址吗？

**Comment by GaoHuanCUG** [comment]
The user faces issues when compiling Alglib. The source of Alglib was uploaded in the directory named "alglib", but it lacks a NULL header file named "stdafx.h". This file is included in the cpp files of Alglib, although it is NULL. We created a new NULL file with the same name to address this issue. You may also just delete the line (#include "stdafx.h") to address it.
